"""Parse a Common Paper template into verbatim Standard Terms blocks (PL-5).

The legal text is reproduced faithfully from the template files — it is never
generated by the LLM. Templates mark structure with ``<span class="header_2">``
/ ``header_3`` (section headings) and other ``<span>`` / ``<label>`` wrappers
that we unwrap for display, keeping the underlying text and numbering.
"""

from __future__ import annotations

import os
import re
from functools import lru_cache
from pathlib import Path

LABEL_RE = re.compile(r"<label>.*?</label>", re.DOTALL)
HEADER_SPAN_RE = re.compile(r'<span class="header_[23]"[^>]*>(.*?)</span>', re.DOTALL)
SPAN_RE = re.compile(r"<span[^>]*>(.*?)</span>", re.DOTALL)
MARKER_RE = re.compile(r"^([0-9]+\.|[a-zA-Z]\.)\s+")


def templates_dir() -> Path:
    return Path(
        os.environ.get(
            "TEMPLATES_DIR", str(Path(__file__).resolve().parents[2] / "templates")
        )
    )


def _unwrap_spans(text: str) -> str:
    return SPAN_RE.sub(lambda m: m.group(1), text)


def _parse_line(line: str) -> dict | None:
    indent = len(line) - len(line.lstrip(" "))
    body = LABEL_RE.sub("", line).strip()
    if not body:
        return None

    level = indent // 4

    # Markdown heading (e.g. the "## USING THIS ..." intro). Skip the top H1
    # document title since the UI renders its own.
    if body.startswith("#"):
        hashes = len(body) - len(body.lstrip("#"))
        heading = _unwrap_spans(body.lstrip("#").strip())
        if hashes <= 1:
            return None
        return {"level": level, "number": "", "heading": heading, "text": ""}

    number = ""
    marker = MARKER_RE.match(body)
    if marker:
        number = marker.group(1)
        body = body[marker.end():]

    heading = ""
    header = HEADER_SPAN_RE.match(body)
    if header:
        heading = _unwrap_spans(header.group(1)).strip()
        body = body[header.end():]

    text = _unwrap_spans(body).strip()
    if not (number or heading or text):
        return None
    return {"level": level, "number": number, "heading": heading, "text": text}


@lru_cache(maxsize=None)
def parse_terms(template_file: str) -> tuple[dict, ...]:
    """Return the template's Standard Terms as ordered, display-ready blocks."""
    path = templates_dir() / template_file
    raw = path.read_text(encoding="utf-8")
    blocks: list[dict] = []
    for line in raw.splitlines():
        block = _parse_line(line)
        if block is not None:
            blocks.append(block)
    return tuple(blocks)
